<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Regiones, Ciudades y Comunas de Chile
    |--------------------------------------------------------------------------
    |
    | Listado completo de ubicaciones de Chile para selección en formularios
    |
    */

    'regiones' => [
        'Región Metropolitana' => [
            'Santiago' => [
                'Santiago Centro',
                'Cerrillos',
                'Cerro Navia',
                'Conchalí',
                'El Bosque',
                'Estación Central',
                'Huechuraba',
                'Independencia',
                'La Cisterna',
                'La Florida',
                'La Granja',
                'La Pintana',
                'La Reina',
                'Las Condes',
                'Lo Barnechea',
                'Lo Espejo',
                'Lo Prado',
                'Macul',
                'Maipú',
                'Ñuñoa',
                'Pedro Aguirre Cerda',
                'Peñalolén',
                'Providencia',
                'Pudahuel',
                'Quilicura',
                'Quinta Normal',
                'Recoleta',
                'Renca',
                'San Joaquín',
                'San Miguel',
                'San Ramón',
                'Vitacura',
            ],
            'Cordillera' => [
                'Pirque',
                'Puente Alto',
                'San José de Maipo',
            ],
            'Maipo' => [
                'Buin',
                'Calera de Tango',
                'Paine',
                'San Bernardo',
            ],
            'Melipilla' => [
                'Alhué',
                'Curacaví',
                'María Pinto',
                'Melipilla',
                'San Pedro',
            ],
            'Talagante' => [
                'El Monte',
                'Isla de Maipo',
                'Padre Hurtado',
                'Peñaflor',
                'Talagante',
            ],
            'Chacabuco' => [
                'Colina',
                'Lampa',
                'Tiltil',
            ],
        ],
        
        'Valparaíso' => [
            'Valparaíso' => [
                'Valparaíso',
                'Casablanca',
                'Concón',
                'Juan Fernández',
                'Puchuncaví',
                'Quintero',
                'Viña del Mar',
            ],
            'Isla de Pascua' => [
                'Isla de Pascua',
            ],
            'Los Andes' => [
                'Calle Larga',
                'Los Andes',
                'Rinconada',
                'San Esteban',
            ],
            'Petorca' => [
                'Cabildo',
                'La Ligua',
                'Papudo',
                'Petorca',
                'Zapallar',
            ],
            'Quillota' => [
                'Hijuelas',
                'La Calera',
                'La Cruz',
                'Nogales',
                'Quillota',
            ],
            'San Antonio' => [
                'Algarrobo',
                'Cartagena',
                'El Quisco',
                'El Tabo',
                'San Antonio',
                'Santo Domingo',
            ],
            'San Felipe de Aconcagua' => [
                'Catemu',
                'Llaillay',
                'Panquehue',
                'Putaendo',
                'San Felipe',
                'Santa María',
            ],
            'Marga Marga' => [
                'Limache',
                'Olmué',
                'Quilpué',
                'Villa Alemana',
            ],
        ],

        'Biobío' => [
            'Concepción' => [
                'Concepción',
                'Coronel',
                'Chiguayante',
                'Florida',
                'Hualqui',
                'Lota',
                'Penco',
                'San Pedro de la Paz',
                'Santa Juana',
                'Talcahuano',
                'Tomé',
                'Hualpén',
            ],
            'Arauco' => [
                'Arauco',
                'Cañete',
                'Contulmo',
                'Curanilahue',
                'Lebu',
                'Los Álamos',
                'Tirúa',
            ],
            'Biobío' => [
                'Alto Biobío',
                'Antuco',
                'Cabrero',
                'Laja',
                'Los Ángeles',
                'Mulchén',
                'Nacimiento',
                'Negrete',
                'Quilaco',
                'Quilleco',
                'San Rosendo',
                'Santa Bárbara',
                'Tucapel',
                'Yumbel',
            ],
            'Ñuble' => [
                'Bulnes',
                'Chillán',
                'Chillán Viejo',
                'Cobquecura',
                'Coelemu',
                'Coihueco',
                'El Carmen',
                'Ninhue',
                'Ñiquén',
                'Pemuco',
                'Pinto',
                'Portezuelo',
                'Quillón',
                'Quirihue',
                'Ránquil',
                'San Carlos',
                'San Fabián',
                'San Ignacio',
                'San Nicolás',
                'Treguaco',
                'Yungay',
            ],
        ],

        'Otras Regiones' => [
            'Otras' => [
                'Otra comuna',
            ],
        ],
    ],
];
